version: '3.8'
services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile.dev   # Use the development Dockerfile
    ports:
      - "3009:3001"
    env_file:
      - ./service1/.env
    volumes:
      - ./service1:/usr/src/app           # Mount local source code
      - service1_node_modules:/usr/src/app/node_modules  # Use a named volume for node_modules
    networks:
      - dingdong
  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile.dev   # Use a similar dev Dockerfile
    ports:
      - "3008:3002"
    env_file:
      - ./service2/.env
    depends_on:
      - redis
    volumes:
      - ./service2:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dingdong

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dingdong

  api-gateway:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1
      - service2
    networks:
      - dingdong

networks:
  dingdong:
    driver: bridge

volumes:
  service1_node_modules:
