version: '3.8'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "3009:3001"
    env_file:
      - ./service1/.env
    networks:
      - backend

  service2:
    build:
      context: ./service2
    ports:
      - "3008:3002"
    env_file:
      - ./service2/.env
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  api-gateway:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1
      - service2
    networks:
      - backend

networks:
  backend:
    driver: bridge
