
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: prathm0025/srv1:v3
          ports:
            - containerPort: 3001
          resources:  # Added resources section
            requests:
              cpu: "100m"   # Request 100 millicores (0.1 CPU)
              memory: "128Mi"
            limits:
              cpu: "500m"   # Limit to 500 millicores (0.5 CPU)
              memory: "256Mi"
          env:  # ✅ Correct structure
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: "development"
            - name: JWT_SECRET
              value: "secret"
            - name: JWT_REFRESH_SECRET
              value: "secret"
            - name: MONGODB_URI
              value: "mongodb+srv://rohit:1LsyddOtnxWNs1sR@og.bkzn1.mongodb.net/?retryWrites=true&w=majority&appName=OG/test"
            - name: ROOT_ROLE
              value: "admin"
            - name: ROOT_NAME
              value: "Administrator"
            - name: ROOT_USERNAME
              value: "admin"
            - name: ROOT_PASSWORD
              value: "admin123"
            - name: CLOUDINARY_CLOUD_NAME
              value: "dcrokdpjt"
            - name: CLOUDINARY_API_KEY
              value: "855758799355978"
            - name: CLOUDINARY_API_SECRET
              value: "NvkyYVIoiWjtfYFyNlJ-ZxtjB90"

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001  # NodePort must be in range 30000-32767
