apiVersion: v1
kind: Secret
metadata:
  name: service1-secrets
type: Opaque
data:
  JWT_SECRET: c2VjcmV0
  JWT_REFRESH_SECRET: c2VjcmV0
  MONGODB_URI: bW9uZ29kYitzcnY6cm9oaXQ6MUxzeWRkT3RueFdOczFzUkBvZy5iazFucy5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZQ==
  ROOT_ROLE: YWRtaW4=
  ROOT_NAME: QWRtaW5pc3RyYXRvcg==
  ROOT_USERNAME: YWRtaW4=
  ROOT_PASSWORD: YWRtaW4xMjM=
  CLOUDINARY_CLOUD_NAME: ZGNyb2tkcGp0
  CLOUDINARY_API_KEY: ODg1NzU4Nzk5MzU1OTc4
  CLOUDINARY_API_SECRET: TnZreVlWSW9pV2p0ZllGeU5sSi1aeHRqQjkw
