apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: prathm0025/srv2:v2
          ports:
            - containerPort: 3002
          resources:  # Added resources section
            requests:
              cpu: "100m"   # Request 100 millicores (0.1 CPU)
              memory: "128Mi"
            limits:
              cpu: "500m"   # Limit to 500 millicores (0.5 CPU)
              memory: "256Mi"
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  selector:
    app: service2
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
